### ISSUE TITLE
Fix phpcs support

### ISSUE THREAD

**Issue by tedsecretsource** [SecretSourceWeb/ratify#3] opened 2019-05-01 12:36 UTC
Currently, phpcs requires manual installation and configuration. WPRig uses phpcs as well but doesn't require anything more than composer install and npm run build. There should be a way to use a local version with vscode. See composer.json and package.json in wprig for some ideas.

**Comment by tedsecretsource** [comment] 2019-05-02 10:46
Using the most recent commit (35b41f4), tried a fresh install followed by both `composer install` and `npm install`. installed_paths had correct values (paths) in the CodeSniffer.conf file but vscode was returning the error: 

```
phpcs: Unable to locate phpcs.
Command failed: "/mnt/hd/user/workspace/wordpress/ratify" --version /bin/sh: 1: /mnt/hd/user/workspace/wordpress/ratify: Permission denied
```

Still working on this.

**Comment by tedmasterweb** [comment] 2019-05-08 11:22
vscode requires that you open the Ratify plugin folder. If you open a folder above the Ratify folder and then expand it to open a file, phpcs will complain with an error, possibly "cannot locate 'phpcs'" or something similar. That said, this is not the cause of the error above. We believe the error above is due to a specific configuration issue of the machine we tested on and that's why we're closing this issue (because it's a machine configuration issue and not an issue with this repository).

**Closed as completed by tedmasterweb** 2019-05-08 11:22 UTC
Labels: enhancement
